name: Docker

on:
  push:
    branches:
      - master

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version:
          - '14'
          - '14.4'
          - '14.4.0'
          - '14.5'
          - '14.5.0'
          - '14.6'
          - '14.6.0'
          - '14.7'
          - '14.7.0'
          - '14.8'
          - '14.8.0'
          - '14.9'
          - '14.9.0'
          - '14.10'
          - '14.10.0'
          - '14.10.1'
          - '14.11'
          - '14.11.0'
          - '14.12'
          - '14.12.0'

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          context: ./node
          build_args:  NODE_VERSION=${{ matrix.node_version }}
          repository: ${{ github.repository }}/node
          tags: ${{ matrix.node_version }}
